[engine]
rate = 20
duration = "605000s"
cap = 6
accounts = 600000
alive = 200000

[client]
script = "benchmark/ethereum/makerdao/script.lua" # 脚本
type = "eth"                                      # 区块链类型
contract = "benchmark/ethereum/makerdao/contract" # 合约目录路径
config = "benchmark/ethereum/makerdao/eth"        # 区块链SDK配置路径
enable_config_contract_address = false            #是否允许配置已部署的合约

[client.options] # 客户端选项

[recorder.log]
dump = false
dir = "./logs"
level = "debug"

[recorder.csv]
dir = "./csv"
