[engine]
rate = 15                        # 速率，重点压测指标
duration = "600s"                # 持续时间
cap = 5                        # 客户端虚拟机数量，类似CPU核心数
accounts = 400000 # 总账户数
alive = 300000

[client]
script = "benchmark/ethereum/compound/script.lua" # 脚本
type = "eth"                                      # 区块链类型
contract = "benchmark/ethereum/compound/contract" # 合约目录路径
config = "benchmark/ethereum/compound/eth"        # 区块链SDK配置路径

[client.options] # 客户端选项

[recorder.log]
dump = false
dir = "./logs"
level = "info"

[recorder.csv]
dir = "./csv"