[engine]
rate = 1                        # 速率，重点压测指标
duration = "30s"                # 持续时间
cap = 1                        # 客户端虚拟机数量，类似CPU核心数
accounts = 200                 # 总账户数

[client]
script = "benchmark/ethereum/compound/script.lua" # 脚本
type = "eth"                                      # 区块链类型
contract = "benchmark/ethereum/compound/contract" # 合约目录路径
config = "benchmark/ethereum/compound/eth"        # 区块链SDK配置路径

[client.options] # 客户端选项

[recorder.log]
dump = false
dir = "./logs"
level = "info"

[recorder.csv]
dir = "./csv"