[engine]
rate = 1
duration = "30s"
cap = 1
accounts = 100

[client]
script = "benchmark/ethereum/curve/script.lua"     # 脚本
type = "eth"                                        # 区块链类型
contract = "benchmark/ethereum/curve/contract"     # 合约目录路径
config = "benchmark/ethereum/curve/eth"            # 区块链SDK配置路径

[client.options] # 客户端选项

[recorder.log]
dump=false
dir="./logs"
level="info"

[recorder.csv]
dir="./csv"





