[engine]
rate = 440
duration = "605000s"
cap = 142
accounts = 600000
alive = 200000

[client]
script = "benchmark/ethereum/transfer/script.lua"   # 脚本
type = "eth"                                        # 区块链类型
config = "benchmark/ethereum/transfer/eth"          # 区块链SDK配置路径
plugin = "./eth.so"                                 # 插件路径

[client.options] # 客户端选项

[recorder.log]
dump=false
dir="./logs"
level="info"

[recorder.csv]
dir="./csv"





