[engine]
rate = 10
duration = "10s"
cap = 100
accounts = 10000

[client]
script = "benchmark/ethereum/transfer/script.lua"   # 脚本
type = "eth"                                        # 区块链类型
config = "benchmark/ethereum/transfer/eth"          # 区块链SDK配置路径
plugin = "./eth.so"                                 # 插件路径

[client.options] # 客户端选项

[recorder.log]
dump=false
dir="./logs"
level="debug"

[recorder.csv]
dir="./csv"





