[engine]
rate = 2                        # 速率，重点压测指标
duration = "168h"                # 持续时间
cap = 2                          # 客户端虚拟机数量，类似CPU核心数
accounts = 20                   #

[client]
script = "benchmark/ethereum/stability-transfer/script.lua"   # 脚本
type = "eth"                                        # 区块链类型
config = "benchmark/ethereum/stability-transfer/eth"          # 区块链SDK配置路径
plugin = "./eth.so"                                 # 插件路径

[client.options] # 客户端选项

[recorder.log]
dump=false
dir="./logs"
level="info"

[recorder.csv]
dir="./csv"





